// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Greenfield BSC Archiver Service API
//
//	API for handling block query in the Greenfield BSC Archiver.
//	Schemes:
//	  http
//	Host: greenfield-bsc-archiver
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
