// Code generated by go-swagger; DO NOT EDIT.

package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"greeenfield-bsc-archiver/models"
)

// GetBlockByHashOKCode is the HTTP code returned for type GetBlockByHashOK
const GetBlockByHashOKCode int = 200

/*
GetBlockByHashOK successful operation

swagger:response getBlockByHashOK
*/
type GetBlockByHashOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetBlockByHashRPCResponse `json:"body,omitempty"`
}

// NewGetBlockByHashOK creates GetBlockByHashOK with default headers values
func NewGetBlockByHashOK() *GetBlockByHashOK {

	return &GetBlockByHashOK{}
}

// WithPayload adds the payload to the get block by hash o k response
func (o *GetBlockByHashOK) WithPayload(payload *models.GetBlockByHashRPCResponse) *GetBlockByHashOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block by hash o k response
func (o *GetBlockByHashOK) SetPayload(payload *models.GetBlockByHashRPCResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockByHashOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlockByHashInternalServerErrorCode is the HTTP code returned for type GetBlockByHashInternalServerError
const GetBlockByHashInternalServerErrorCode int = 500

/*
GetBlockByHashInternalServerError internal server error

swagger:response getBlockByHashInternalServerError
*/
type GetBlockByHashInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlockByHashInternalServerError creates GetBlockByHashInternalServerError with default headers values
func NewGetBlockByHashInternalServerError() *GetBlockByHashInternalServerError {

	return &GetBlockByHashInternalServerError{}
}

// WithPayload adds the payload to the get block by hash internal server error response
func (o *GetBlockByHashInternalServerError) WithPayload(payload *models.Error) *GetBlockByHashInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block by hash internal server error response
func (o *GetBlockByHashInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockByHashInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
