// Code generated by go-swagger; DO NOT EDIT.

package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"greeenfield-bsc-archiver/models"
)

// GetBlockByNumberSimplifiedOKCode is the HTTP code returned for type GetBlockByNumberSimplifiedOK
const GetBlockByNumberSimplifiedOKCode int = 200

/*
GetBlockByNumberSimplifiedOK successful operation

swagger:response getBlockByNumberSimplifiedOK
*/
type GetBlockByNumberSimplifiedOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetBlockByNumberSimplifiedRPCResponse `json:"body,omitempty"`
}

// NewGetBlockByNumberSimplifiedOK creates GetBlockByNumberSimplifiedOK with default headers values
func NewGetBlockByNumberSimplifiedOK() *GetBlockByNumberSimplifiedOK {

	return &GetBlockByNumberSimplifiedOK{}
}

// WithPayload adds the payload to the get block by number simplified o k response
func (o *GetBlockByNumberSimplifiedOK) WithPayload(payload *models.GetBlockByNumberSimplifiedRPCResponse) *GetBlockByNumberSimplifiedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block by number simplified o k response
func (o *GetBlockByNumberSimplifiedOK) SetPayload(payload *models.GetBlockByNumberSimplifiedRPCResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockByNumberSimplifiedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlockByNumberSimplifiedInternalServerErrorCode is the HTTP code returned for type GetBlockByNumberSimplifiedInternalServerError
const GetBlockByNumberSimplifiedInternalServerErrorCode int = 500

/*
GetBlockByNumberSimplifiedInternalServerError internal server error

swagger:response getBlockByNumberSimplifiedInternalServerError
*/
type GetBlockByNumberSimplifiedInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlockByNumberSimplifiedInternalServerError creates GetBlockByNumberSimplifiedInternalServerError with default headers values
func NewGetBlockByNumberSimplifiedInternalServerError() *GetBlockByNumberSimplifiedInternalServerError {

	return &GetBlockByNumberSimplifiedInternalServerError{}
}

// WithPayload adds the payload to the get block by number simplified internal server error response
func (o *GetBlockByNumberSimplifiedInternalServerError) WithPayload(payload *models.Error) *GetBlockByNumberSimplifiedInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block by number simplified internal server error response
func (o *GetBlockByNumberSimplifiedInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockByNumberSimplifiedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
