// Code generated by go-swagger; DO NOT EDIT.

package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"greeenfield-bsc-archiver/models"
)

// GetBlockNumberOKCode is the HTTP code returned for type GetBlockNumberOK
const GetBlockNumberOKCode int = 200

/*
GetBlockNumberOK successful operation

swagger:response getBlockNumberOK
*/
type GetBlockNumberOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetBlockNumberRPCResponse `json:"body,omitempty"`
}

// NewGetBlockNumberOK creates GetBlockNumberOK with default headers values
func NewGetBlockNumberOK() *GetBlockNumberOK {

	return &GetBlockNumberOK{}
}

// WithPayload adds the payload to the get block number o k response
func (o *GetBlockNumberOK) WithPayload(payload *models.GetBlockNumberRPCResponse) *GetBlockNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block number o k response
func (o *GetBlockNumberOK) SetPayload(payload *models.GetBlockNumberRPCResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlockNumberInternalServerErrorCode is the HTTP code returned for type GetBlockNumberInternalServerError
const GetBlockNumberInternalServerErrorCode int = 500

/*
GetBlockNumberInternalServerError internal server error

swagger:response getBlockNumberInternalServerError
*/
type GetBlockNumberInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlockNumberInternalServerError creates GetBlockNumberInternalServerError with default headers values
func NewGetBlockNumberInternalServerError() *GetBlockNumberInternalServerError {

	return &GetBlockNumberInternalServerError{}
}

// WithPayload adds the payload to the get block number internal server error response
func (o *GetBlockNumberInternalServerError) WithPayload(payload *models.Error) *GetBlockNumberInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block number internal server error response
func (o *GetBlockNumberInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockNumberInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
