// Code generated by go-swagger; DO NOT EDIT.

package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBlockNumberHandlerFunc turns a function with the right signature into a get block number handler
type GetBlockNumberHandlerFunc func(GetBlockNumberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBlockNumberHandlerFunc) Handle(params GetBlockNumberParams) middleware.Responder {
	return fn(params)
}

// GetBlockNumberHandler interface for that can handle valid get block number params
type GetBlockNumberHandler interface {
	Handle(GetBlockNumberParams) middleware.Responder
}

// NewGetBlockNumber creates a new http.Handler for the get block number operation
func NewGetBlockNumber(ctx *middleware.Context, handler GetBlockNumberHandler) *GetBlockNumber {
	return &GetBlockNumber{Context: ctx, Handler: handler}
}

/*
	GetBlockNumber swagger:route POST /eth_blockNumber block getBlockNumber

Returns the latest block number of the blockchain
*/
type GetBlockNumber struct {
	Context *middleware.Context
	Handler GetBlockNumberHandler
}

func (o *GetBlockNumber) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBlockNumberParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
