// Code generated by go-swagger; DO NOT EDIT.

package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBundledBlockByNumberHandlerFunc turns a function with the right signature into a get bundled block by number handler
type GetBundledBlockByNumberHandlerFunc func(GetBundledBlockByNumberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBundledBlockByNumberHandlerFunc) Handle(params GetBundledBlockByNumberParams) middleware.Responder {
	return fn(params)
}

// GetBundledBlockByNumberHandler interface for that can handle valid get bundled block by number params
type GetBundledBlockByNumberHandler interface {
	Handle(GetBundledBlockByNumberParams) middleware.Responder
}

// NewGetBundledBlockByNumber creates a new http.Handler for the get bundled block by number operation
func NewGetBundledBlockByNumber(ctx *middleware.Context, handler GetBundledBlockByNumberHandler) *GetBundledBlockByNumber {
	return &GetBundledBlockByNumber{Context: ctx, Handler: handler}
}

/*
	GetBundledBlockByNumber swagger:route POST /eth_getBundledBlockByNumber block getBundledBlockByNumber

Returns information of the block bundle matching the given block number.
*/
type GetBundledBlockByNumber struct {
	Context *middleware.Context
	Handler GetBundledBlockByNumberHandler
}

func (o *GetBundledBlockByNumber) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBundledBlockByNumberParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
