// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Withdrawal withdrawal
//
// swagger:model Withdrawal
type Withdrawal struct {

	// address
	// Example: 0x1234567890abcdef1234567890abcdef12345678
	Address string `json:"Address,omitempty"`

	// amount
	// Example: 1000000
	Amount string `json:"Amount,omitempty"`

	// index
	// Example: 1
	Index string `json:"Index,omitempty"`

	// validator
	// Example: 12345
	Validator string `json:"Validator,omitempty"`
}

// Validate validates this withdrawal
func (m *Withdrawal) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this withdrawal based on context it is used
func (m *Withdrawal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Withdrawal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Withdrawal) UnmarshalBinary(b []byte) error {
	var res Withdrawal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
